apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bagua-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bagua-role
subjects:
- kind: ServiceAccount
  name: bagua-account
  namespace: bagua
