apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bagua
  name: bagua-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bagua-operator
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: bagua-operator
    spec:
      containers:
      - name: ares-operator
        image: baguasys/operator:latest
        imagePullPolicy: "IfNotPresent"
        workingDir: /home/work
        command:
          - ./manager
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP
        readinessProbe:
          httpGet:
            path:
              /readyz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path:
              /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
