# TODO
apiVersion: bagua.kuaishou.com/v1alpha1
kind: Bagua
metadata:
  name: bagua-sample-elastic
spec:
  enableElastic: true
  minReplicas: 1
  maxReplicas: 5
  replicaSpecs:
    etcd:
      replicas: 1
      template:
        spec:
          hostNetwork: true
          containers:
            - name: bagua
              image: golang:1.15
              imagePullPolicy: IfNotPresent
              command:
                - sleep
                - 1d
              ports:
                - containerPort: 12345
    worker:
      replicas: 3
      template:
        spec:
          hostNetwork: true
          containers:
            - name: bagua
              image: golang:1.15
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - sleep 1d
              
            